### ISSUE TITLE
Windowslogoff not found

### ISSUE THREAD

**Issue by LESARQ** [MohammadYounes/MVC5-MixedAuth#40]
Hey,

I've implemented this branch on multiple projects and it works all the time.
But, in one of my customers, after inserting the domain account it gives an error about not finding Windowslogoff.

It's problably a Windows/IIS feature, but I can't simulate it on my DEV machine.

Any ideas? How may i be able do discover what's causing it?

**Comment by MohammadYounes** [comment]
Hi,

It's hard to tell without details, Can you provide a stack trace or some debug info ?

**Comment by LESARQ** [comment]
I will be at a conference call with them at in 1h30. If i don't find anything i will give you the stacktrace, can't do it now because I don't have it.

Thank you for your time, in 3-4h I'll give you feedback and if I find the problem I'll post the solution here.

**Comment by LESARQ** [comment]
Oh, i forgot to say that "Windowslogoff" is called It's on [WindowsLoginHandler](https://github.com/MohammadYounes/MVC5-MixedAuth/blob/master/src/Windows/WindowsLoginHandler.cs) line 45.

But in my Account controller, there is only one action to logoff an it's a Post. Could it be the problem? Since it doesn't specify Get or Post i assume that Get is the default.

**Comment by MohammadYounes** [comment]
Most probably, you can't call a Post action using Get.

**Comment by LESARQ** [comment]
But I didn't change that part of the code from that file?

**Comment by MohammadYounes** [comment]
I'm lost now, you have made no changes to account controller nor to windows login handler and you get an error about not finding Windowslogoff ?

**Comment by LESARQ** [comment]
Yes. WindowsLoginHandler and MixedAuthExtensions are exactly the same as mine.
AccountController have some differences, but my WindowsLogOff action is the same.

In this branch's [Account controller](https://github.com/MohammadYounes/MVC5-MixedAuth/blob/master/src/Controllers/AccountController.Windows.cs) WindowsLogOff is marked as Post and so do mine.

**Comment by MohammadYounes** [comment]
It's hard to guess without detailed error information. What's the exact error message you are getting ?

Is it _unknonw action value 'WindowsLogoff'_ ?

**Comment by LESARQ** [comment]
WindowsLogoff not found in Windows Controller.

**Comment by MohammadYounes** [comment]
I think it's better to wait till you get detailed info about this :)

**Comment by LESARQ** [comment]
Hey, i resolved it.

Webconfig changed:
`<authentication mode="Windows" /> `
to
`<authentication mode="None" /> `

they changed it by themselves...

However, it doesn't explain the error about not finding the action and they didn't send me the stacktrace...

**Comment by LESARQ** [comment]
Thank you for this awesome handler!
Sorry about all the confusion.

**Comment by MohammadYounes** [comment]
Thanks for the feedback! May be simulate it on your DEV machine and find out if you get the same behavior :)

**Comment by LESARQ** [comment]
With `mode="Windows"`, `context.User.Identity.IsAuthenticated` is always true.

**Comment by MohammadYounes** [comment]
Did you get the same error ?

**Comment by LESARQ** [comment]
Yes.

> A public action method 'WindowsLogOff' was not found on controller '<PROJECTNAME>.Controllers.AccountController'.

 ```
  at System.Web.Mvc.Controller.HandleUnknownAction(String actionName)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MixedAuth.WindowsLoginHandler.<ExecuteController>d__10.MoveNext() in c:\<...>\Infrastructure\WindowsLogin\WindowsLoginHandler.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MixedAuth.WindowsLoginHandler.<WinLogoffAsync>d__c.MoveNext() in c:\<...>\Infrastructure\WindowsLogin\WindowsLoginHandler.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MixedAuth.WindowsLoginHandler.<ProcessRequestAsync>d__0.MoveNext() in c:\<...>\Infrastructure\WindowsLogin\WindowsLoginHandler.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

**Comment by MohammadYounes** [comment]
Thanks, very much appreciated.
